import { Items } from './entities/items.entity';

export const ItemsSeed: Partial<Items>[] = [
  //! 배치물
  {
    name: '쓰레기통',
    type: 'default',
    data: 'static/default/wastecan.svg',
    point: 0,
  },
  //! 테마
  {
    name: '바다속',
    type: 'theme',
    data: 'static/theme/ocean.jpg',
    point: 0,
  },
  {
    name: '방1',
    type: 'theme',
    data: 'static/theme/home.jpg',
    point: 0,
  },
  {
    name: '우주',
    type: 'theme',
    data: 'static/theme/space.jpg',
    point: 100,
  },
  {
    name: '집',
    type: 'theme',
    data: 'static/theme/house.jpg',
    point: 0,
  },
  {
    name: '정원',
    type: 'theme',
    data: 'static/theme/ground.jpg',
    point: 100,
  },
  {
    name: '아침',
    type: 'theme',
    data: 'static/theme/morning.jpg',
    point: 100,
  },
  {
    name: '자연',
    type: 'theme',
    data: 'static/theme/nature.jpg',
    point: 100,
  },

  {
    name: '방2',
    type: 'theme',
    data: 'static/theme/room.jpg',
    point: 100,
  },
  {
    name: '방3',
    type: 'theme',
    data: 'static/theme/room2.jpg',
    point: 100,
  },
  {
    name: '해변',
    type: 'theme',
    data: 'static/theme/beach.jpg',
    point: 200,
  },
  {
    name: '빌딩',
    type: 'theme',
    data: 'static/theme/building.jpg',
    point: 200,
  },
  {
    name: '성',
    type: 'theme',
    data: 'static/theme/castle.jpg',
    point: 200,
  },
  {
    name: '도시',
    type: 'theme',
    data: 'static/theme/city.jpg',
    point: 200,
  },
  {
    name: '농장',
    type: 'theme',
    data: 'static/theme/farm.jpg',
    point: 200,
  },
  {
    name: '숲',
    type: 'theme',
    data: 'static/theme/forest.jpg',
    point: 200,
  },
  {
    name: '밤',
    type: 'theme',
    data: 'static/theme/night.jpg',
    point: 200,
  },
  {
    name: '학교',
    type: 'theme',
    data: 'static/theme/school.jpg',
    point: 200,
  },
  {
    name: '거리1',
    type: 'theme',
    data: 'static/theme/street.jpg',
    point: 300,
  },
  {
    name: '거리2',
    type: 'theme',
    data: 'static/theme/street2.jpg',
    point: 300,
  },
  {
    name: '여름',
    type: 'theme',
    data: 'static/theme/summer.jpg',
    point: 400,
  },
  {
    name: '해질녘',
    type: 'theme',
    data: 'static/theme/sunset.jpg',
    point: 400,
  },
  //!이미지
  {
    name: '생일축하1',
    type: 'img',
    data: 'static/img/birthday.jpg',
    point: 0,
  },
  {
    name: '선물상자1',
    type: 'img',
    data: 'static/img/giftbox(1).jpg',
    point: 0,
  },
  {
    name: '선물상자2',
    type: 'img',
    data: 'static/img/giftbox(2).jpg',
    point: 0,
  },
  {
    name: '선물상자3',
    type: 'img',
    data: 'static/img/giftbox(3).jpg',
    point: 0,
  },
  {
    name: '선물은나야',
    type: 'img',
    data: 'static/img/itsme.jpg',
    point: 100,
  },
  {
    name: '선물교환권',
    type: 'img',
    data: 'static/img/gun.jpg',
    point: 100,
  },
  {
    name: '나이',
    type: 'img',
    data: 'static/img/age.jpg',
    point: 100,
  },
  {
    name: '부자되세요',
    type: 'img',
    data: 'static/img/toberich.jpg',
    point: 100,
  },
  {
    name: '돈다발',
    type: 'img',
    data: 'static/img/moneyflower.jpg',
    point: 100,
  },
  {
    name: '가즈아',
    type: 'img',
    data: 'static/img/go.jpg',
    point: 100,
  },
  {
    name: '꿈은없고요',
    type: 'img',
    data: 'static/img/dream.jpg',
    point: 100,
  },
  {
    name: '한심한녀석',
    type: 'img',
    data: 'static/img/you.png',
    point: 150,
  },
  {
    name: '어쩌면좋지',
    type: 'img',
    data: 'static/img/how.png',
    point: 150,
  },

  {
    name: '바보',
    type: 'img',
    data: 'static/img/babo.gif',
    point: 200,
  },
  {
    name: '빵야',
    type: 'img',
    data: 'static/img/bbang.gif',
    point: 200,
  },
  {
    name: '생일축하2',
    type: 'img',
    data: 'static/img/birthday2.gif',
    point: 200,
  },
  {
    name: '아톰',
    type: 'img',
    data: 'static/img/atom.gif',
    point: 200,
  },
  {
    name: '배',
    type: 'img',
    data: 'static/img/boat.gif',
    point: 250,
  },
  {
    name: '축하',
    type: 'img',
    data: 'static/img/chuka.gif',
    point: 250,
  },
  {
    name: '춤1',
    type: 'img',
    data: 'static/img/dance.gif',
    point: 250,
  },
  {
    name: 'destroy',
    type: 'img',
    data: 'static/img/destroy.gif',
    point: 250,
  },
  {
    name: '울지마1',
    type: 'img',
    data: 'static/img/destroy.gif',
    point: 250,
  },

  {
    name: '드라이브',
    type: 'img',
    data: 'static/img/drive.gif',
    point: 300,
  },
  {
    name: '고라파덕',
    type: 'img',
    data: 'static/img/duck.gif',
    point: 300,
  },
  {
    name: '춤2',
    type: 'img',
    data: 'static/img/food.gif',
    point: 300,
  },
  {
    name: '신난다',
    type: 'img',
    data: 'static/img/fun.gif',
    point: 300,
  },
  {
    name: 'hey',
    type: 'img',
    data: 'static/img/hey.gif',
    point: 300,
  },

  {
    name: '울지마2',
    type: 'img',
    data: 'static/img/hug.gif',
    point: 400,
  },
  {
    name: '맙소사',
    type: 'img',
    data: 'static/img/no.gif',
    point: 400,
  },
  {
    name: '펭수',
    type: 'img',
    data: 'static/img/pengsu.gif',
    point: 400,
  },
  {
    name: '피카츄',
    type: 'img',
    data: 'static/img/picnic.gif',
    point: 400,
  },
  {
    name: '짱구수영',
    type: 'img',
    data: 'static/img/swim.gif',
    point: 400,
  },
  {
    name: 'ㅎㄷㄷ',
    type: 'img',
    data: 'static/img/wow.gif',
    point: 400,
  },
  //!SVG
  {
    name: '선물상자1',
    type: 'svg',
    data: 'static/svg/giftbox1.svg',
    point: 0,
  },
  {
    name: '선물상자2',
    type: 'svg',
    data: 'static/svg/giftbox2.svg',
    point: 0,
  },
  {
    name: '주머니',
    type: 'svg',
    data: 'static/svg/pocket.svg',
    point: 0,
  },
  {
    name: '메달1',
    type: 'svg',
    data: 'static/svg/medal1.svg',
    point: 0,
  },
  {
    name: '선물상자3',
    type: 'svg',
    data: 'static/svg/giftbox3.svg',
    point: 100,
  },
  {
    name: '선물상자4',
    type: 'svg',
    data: 'static/svg/giftbox4.svg',
    point: 100,
  },
  {
    name: '선물상자5',
    type: 'svg',
    data: 'static/svg/giftbox5.svg',
    point: 100,
  },
  {
    name: '선물상자6',
    type: 'svg',
    data: 'static/svg/giftbox6.svg',
    point: 100,
  },
  {
    name: '하트1',
    type: 'svg',
    data: 'static/svg/heart1.svg',
    point: 150,
  },
  {
    name: '하트2',
    type: 'svg',
    data: 'static/svg/heart2.svg',
    point: 150,
  },
  {
    name: '메달2',
    type: 'svg',
    data: 'static/svg/medal2.svg',
    point: 150,
  },
  {
    name: '메달3',
    type: 'svg',
    data: 'static/svg/medal3.svg',
    point: 150,
  },
  {
    name: '고양이1',
    type: 'svg',
    data: 'static/svg/cat1.svg',
    point: 200,
  },
  {
    name: '고양이2',
    type: 'svg',
    data: 'static/svg/cat2.svg',
    point: 200,
  },
  {
    name: '고양이3',
    type: 'svg',
    data: 'static/svg/cat3.svg',
    point: 200,
  },
  {
    name: '강아지1',
    type: 'svg',
    data: 'static/svg/dog1.svg',
    point: 200,
  },
  {
    name: '강아지2',
    type: 'svg',
    data: 'static/svg/dog2.svg',
    point: 200,
  },
  {
    name: '동전',
    type: 'svg',
    data: 'static/svg/coin.svg',
    point: 250,
  },
  {
    name: '해',
    type: 'svg',
    data: 'static/svg/sun.svg',
    point: 300,
  },
  {
    name: '달',
    type: 'svg',
    data: 'static/svg/moon.svg',
    point: 300,
  },
  {
    name: '별',
    type: 'svg',
    data: 'static/svg/star.svg',
    point: 300,
  },
];
